name: CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
jobs:
  build:
    - uses: actions/setup-go@v3
      with: { go-version: 1.18.4 }

    - uses: actions/checkout@v3

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with: { version: latest }

    - name: Go build
      run: go build -v

    - name: Go test
      run: go test -v ./...
